export const grooveCategories = [
    {
        id: 1,
        name:'One Night',
        image: require('../../assets/images/category1.png')
    },
    {
        id: 2,
        name: "Massage",
        image: require('../../assets/images/category2.png')
    },
    {
        id: 3,
        name: 'Threesome',
        image: require('../../assets/images/category3.png')
    },
    {
        id: 4,
        name: 'Short Night',
        image: require('../../assets/images/category4.png')
    },
    {
        id: 5,
        name: 'Half Day',
        image: require('../../assets/images/category5.png')
    },
    {
        id: 6,
        name: 'Weekend',
        image: require('../../assets/images/category6.png')
    },
    {
        id: 7,
        name: 'Escort',
        image: require('../../assets/images/category7.png')
    },
    {
        id: 8,
        name: 'Stripper',
        image: require('../../assets/images/category8.png')
    }
]

export const bankCodes = [
    { value: "044", name: "Access Bank" },
    { value: "063", name: "Diamond Bank" },
    { value: "084", name: "Enterprise Bank" },
    { value: "070", name: "Fidelity Bank" },
    { value: "011", name: "First Bank of Nigeria" },
    { value: "214", name: "First City Monument Bank" },
    { value: "058", name: "GTBank Plc" },
    { value: "030", name: "Heritage" },
    { value: "301", name: "JAIZ Bank" },
    { value: "082", name: "Keystone Bank" },
    { value: "076", name: "Skye Bank" },
    { value: "068", name: "Standard Chartered Bank" },
    { value: "221", name: "Stanbic IBTC Bank" },
    { value: "232", name: "Sterling Bank" },
    { value: "100", name: "SunTrust Bank" },
    { value: "033", name: "United Bank for Africa" },
    { value: "032", name: "Union Bank" },
    { value: "215", name: "Unity Bank" },
    { value: "035", name: "Wema Bank" },
    { value: "057", name: "Zenith Bank" },
    { value: "559", name: "Coronation Merchant Bank" },
  ];
  

export const durations = [
    {"name": "1 Day"},
    {"name": "2 Days"},
    {"name": "3 Days"},
    {"name": "4 Days"},
    {"name": "5 Days"},
    {"name": "6 Days"},
    {"name": "7 Days"},
    {"name": "8 Days"},
    {"name": "9 Days"},
    {"name": "10 Days"},
]

export const availability = [
    {
        id: 1,
        name: 'Available',
        value: true
    },
    {
        id: 2,
        name: 'Not Available',
        value: false
    }
]

export const heights = [
    { "name": "145cm - 4ft 9", "value": "145cm - 4ft 9" },
    { "name": "147.5cm - 4ft 10", "value": "147.5cm - 4ft 10" },
    { "name": "150cm - 4ft 11", "value": "150cm - 4ft 11" },
    { "name": "152.5cm - 5ft 0", "value": "152.5cm - 5ft 0" },
    { "name": "155cm - 5ft 1", "value": "155cm - 5ft 1" },
    { "name": "157.5cm - 5ft 2", "value": "157.5cm - 5ft 2" },
    { "name": "160cm - 5ft 3", "value": "160cm - 5ft 3" },
    { "name": "162.5cm - 5ft 4", "value": "162.5cm - 5ft 4" },
    { "name": "165cm - 5ft 5", "value": "165cm - 5ft 5" },
    { "name": "167.5cm - 5ft 6", "value": "167.5cm - 5ft 6" },
    { "name": "170cm - 5ft 7", "value": "170cm - 5ft 7" },
    { "name": "172.5cm - 5ft 8", "value": "172.5cm - 5ft 8" },
    { "name": "175cm - 5ft 9", "value": "175cm - 5ft 9" },
    { "name": "177.5cm - 5ft 10", "value": "177.5cm - 5ft 10" },
    { "name": "180cm - 5ft 11", "value": "180cm - 5ft 11" },
    { "name": "182.5cm - 6ft 0", "value": "182.5cm - 6ft 0" },
    { "name": "185cm - 6ft 1", "value": "185cm - 6ft 1" },
    { "name": "187.5cm - 6ft 2", "value": "187.5cm - 6ft 2" },
    { "name": "190cm - 6ft 3", "value": "190cm - 6ft 3" },
    { "name": "192.5cm - 6ft 4", "value": "192.5cm - 6ft 4" }
  ]
  
export const bodyTypes = [
    {"name": "A Few Extra Pounds"},
    {"name": "Athletic"},
    {"name": "Average"},
    {"name": "Curvy"},
    {"name": "Fit"},
    {"name": "Full-Figured"},
    {"name": "Muscular"},
    {"name": "Petite"},
    {"name": "Plus Size"},
    {"name": "Slim"},
    {"name": "Thick"},
];

export const zodiacSigns = [
    {"name": "Aquarius"},
    {"name": "Aries"},
    {"name": "Cancer"},
    {"name": "Capricorn"},
    {"name": "Gemini"},
    {"name": "Leo"},
    {"name": "Libra"},
    {"name": "Pisces"},
    {"name": "Sagittarius"},
    {"name": "Scorpio"},
    {"name": "Taurus"},
    {"name": "Virgo"}
];

export const network = [
    {
        id: 1,
        name: 'MTN'
    },
    {
        id: 2,
        name: 'Airtel',
    },
    {
        id: 3,
        name: 'Glo'
    },
    {
        id: 4,
        name: '9mobile'
    }
]

export const ethnicity = [ 
    {
        id: 1,
        name: 'Yoruba'
    },
    {
        id: 2,
        name: 'Igbo' 
    },
    {
        id: 3,
        name: 'Hausa' 
    },
]

export const sortGrooveStatus = [
    {
        id: 1, 
        name: 'Pending',
      },
      {
        id: 2, 
        name: 'Completed',
      },
      {
        id: 3, 
        name: 'Cancelled',
      }
]

export const sortBy = [
  {
    id: 1, 
    name: 'Latest',
  },
  {
    id: 2, 
    name: 'Trending',
  },
  {
    id: 3, 
    name: 'Popular',
  }
]

export const ages = [
    {
      id: 1,
      age: '25 - 30'
    },
    {
      id: 2,
      age: '30 - 35'
    },
    {
      id: 3,
      age: '35 - 40'
    },
    {
      id: 4,
      age: '45 - 50'
    },
    {
      id: 5,
      age: '55 - 60'
    },
    {
      id: 6,
      age: '60 - 65'
    }
  ]

 export const states = [
    {
        "code": "FC",
        "name": "Abuja",
        "lgas": [
            "Abuja",
            "Kwali",
            "Kuje",
            "Gwagwalada",
            "Bwari",
            "Abaji"
        ]
    },
    {
        "code": "AB",
        "name": "Abia",
        "lgas": [
            "Aba North",
            "Aba South",
            "Arochukwu",
            "Bende",
            "Ikawuno",
            "Ikwuano",
            "Isiala-Ngwa North",
            "Isiala-Ngwa South",
            "Isuikwuato",
            "Umu Nneochi",
            "Obi Ngwa",
            "Obioma Ngwa",
            "Ohafia",
            "Ohaozara",
            "Osisioma",
            "Ugwunagbo",
            "Ukwa West",
            "Ukwa East",
            "Umuahia North",
            "Umuahia South"
        ]
    },
    {
        "code": "AD",
        "name": "Adamawa",
        "lgas": [
            "Demsa",
            "Fufore",
            "Ganye",
            "Girei",
            "Gombi",
            "Guyuk",
            "Hong",
            "Jada",
            "Lamurde",
            "Madagali",
            "Maiha",
            "Mayo-Belwa",
            "Michika",
            "Mubi-North",
            "Mubi-South",
            "Numan",
            "Shelleng",
            "Song",
            "Toungo",
            "Yola North",
            "Yola South"
        ]
    },
    {
        "code": "AK",
        "name": "AkwaIbom",
        "lgas": [
            "Abak",
            "Eastern-Obolo",
            "Eket",
            "Esit-Eket",
            "Essien-Udim",
            "Etim-Ekpo",
            "Etinan",
            "Ibeno",
            "Ibesikpo-Asutan",
            "Ibiono-Ibom",
            "Ika",
            "Ikono",
            "Ikot-Abasi",
            "Ikot-Ekpene",
            "Ini",
            "Itu",
            "Mbo",
            "Mkpat-Enin",
            "Nsit-Atai",
            "Nsit-Ibom",
            "Nsit-Ubium",
            "Obot-Akara",
            "Okobo",
            "Onna",
            "Oron",
            "Oruk Anam",
            "Udung-Uko",
            "Ukanafun",
            "Urue-Offong/Oruko",
            "Uruan",
            "Uyo"
        ]
    },
    {
        "code": "AN",
        "name": "Anambra",
        "lgas": [
            "Aguata",
            "Anambra East",
            "Anambra West",
            "Anaocha",
            "Awka North",
            "Awka South",
            "Ayamelum",
            "Dunukofia",
            "Ekwusigo",
            "Idemili-North",
            "Idemili-South",
            "Ihiala",
            "Njikoka",
            "Nnewi-North",
            "Nnewi-South",
            "Ogbaru",
            "Onitsha-North",
            "Onitsha-South",
            "Orumba-North",
            "Orumba-South"
        ]
    },
    {
        "code": "BA",
        "name": "Bauchi",
        "lgas": [
            "Alkaleri",
            "Bauchi",
            "Bogoro",
            "Damban",
            "Darazo",
            "Dass",
            "Gamawa",
            "Ganjuwa",
            "Giade",
            "Itas Gadau",
            "Jama'Are",
            "Katagum",
            "Kirfi",
            "Misau",
            "Ningi",
            "Shira",
            "Tafawa-Balewa",
            "Toro",
            "Warji",
            "Zaki"
        ]
    },
    {
        "code": "BY",
        "name": "Bayelsa",
        "lgas": [
            "Brass",
            "Ekeremor",
            "Kolokuma Opokuma",
            "Nembe",
            "Ogbia",
            "Sagbama",
            "Southern-Ijaw",
            "Yenagoa"
        ]
    },
    {
        "code": "BE",
        "name": "Benue",
        "lgas": [
            "Ado",
            "Agatu",
            "Apa",
            "Buruku",
            "Gboko",
            "Guma",
            "Gwer-East",
            "Gwer-West",
            "Katsina-Ala",
            "Konshisha",
            "Kwande",
            "Logo",
            "Makurdi",
            "Ogbadibo",
            "Ohimini",
            "Oju",
            "Okpokwu",
            "Otukpo",
            "Tarka",
            "Ukum",
            "Ushongo",
            "Vandeikya"
        ]
    },
    {
        "code": "BO",
        "name": "Borno",
        "lgas": [
            "Abadam",
            "Askira-Uba",
            "Bama",
            "Bayo",
            "Biu",
            "Chibok",
            "Damboa",
            "Dikwa",
            "Gubio",
            "Guzamala",
            "Gwoza",
            "Hawul",
            "Jere",
            "Kaga",
            "Kala Balge",
            "Konduga",
            "Kukawa",
            "Kwaya-Kusar",
            "Mafa",
            "Magumeri",
            "Maiduguri",
            "Marte",
            "Mobbar",
            "Monguno",
            "Ngala",
            "Nganzai",
            "Shani"
        ]
    },
    {
        "code": "CR",
        "name": "CrossRiver",
        "lgas": [
            "Abi",
            "Akamkpa",
            "Akpabuyo",
            "Bakassi",
            "Bekwarra",
            "Biase",
            "Boki",
            "Calabar-Municipal",
            "Calabar-South",
            "Etung",
            "Ikom",
            "Obanliku",
            "Obubra",
            "Obudu",
            "Odukpani",
            "Ogoja",
            "Yakurr",
            "Yala"
        ]
    },
    {
        "code": "DE",
        "name": "Delta",
        "lgas": [
            "Aniocha North",
            "Aniocha-North",
            "Aniocha-South",
            "Bomadi",
            "Burutu",
            "Ethiope-East",
            "Ethiope-West",
            "Ika-North-East",
            "Ika-South",
            "Isoko-North",
            "Isoko-South",
            "Ndokwa-East",
            "Ndokwa-West",
            "Okpe",
            "Oshimili-North",
            "Oshimili-South",
            "Patani",
            "Sapele",
            "Udu",
            "Ughelli-North",
            "Ughelli-South",
            "Ukwuani",
            "Uvwie",
            "Warri South-West",
            "Warri North",
            "Warri South"
        ]
    },
    {
        "code": "EB",
        "name": "Ebonyi",
        "lgas": [
            "Abakaliki",
            "Afikpo-North",
            "Afikpo South (Edda)",
            "Ebonyi",
            "Ezza-North",
            "Ezza-South",
            "Ikwo",
            "Ishielu",
            "Ivo",
            "Izzi",
            "Ohaukwu",
            "Onicha"
        ]
    },
    {
        "code": "ED",
        "name": "Edo",
        "lgas": [
            "Akoko Edo",
            "Egor",
            "Esan-Central",
            "Esan-North-East",
            "Esan-South-East",
            "Esan-West",
            "Etsako-Central",
            "Etsako-East",
            "Etsako-West",
            "Igueben",
            "Ikpoba-Okha",
            "Oredo",
            "Orhionmwon",
            "Ovia-North-East",
            "Ovia-South-West",
            "Owan East",
            "Owan-West",
            "Uhunmwonde"
        ]
    },
    {
        "code": "EK",
        "name": "Ekiti",
        "lgas": [
            "Ado-Ekiti",
            "Efon",
            "Ekiti-East",
            "Ekiti-South-West",
            "Ekiti-West",
            "Emure",
            "Gbonyin",
            "Ido-Osi",
            "Ijero",
            "Ikere",
            "Ikole",
            "Ilejemeje",
            "Irepodun Ifelodun",
            "Ise-Orun",
            "Moba",
            "Oye"
        ]
    },
    {
        "code": "EN",
        "name": "Enugu",
        "lgas": [
            "Aninri",
            "Awgu",
            "Enugu-East",
            "Enugu-North",
            "Enugu-South",
            "Ezeagu",
            "Igbo-Etiti",
            "Igbo-Eze-North",
            "Igbo-Eze-South",
            "Isi-Uzo",
            "Nkanu-East",
            "Nkanu-West",
            "Nsukka",
            "Oji-River",
            "Udenu",
            "Udi",
            "Uzo-Uwani"
        ]
    },
    {
        "code": "GO",
        "name": "Gombe",
        "lgas": [
            "Akko",
            "Balanga",
            "Billiri",
            "Dukku",
            "Funakaye",
            "Gombe",
            "Kaltungo",
            "Kwami",
            "Nafada",
            "Shongom",
            "Yamaltu Deba"
        ]
    },
    {
        "code": "IM",
        "name": "Imo",
        "lgas": [
            "Aboh-Mbaise",
            "Ahiazu-Mbaise",
            "Ehime-Mbano",
            "Ezinihitte",
            "Ideato-North",
            "Ideato-South",
            "Ihitte Uboma",
            "Ikeduru",
            "Isiala-Mbano",
            "Isu",
            "Mbaitoli",
            "Ngor-Okpala",
            "Njaba",
            "Nkwerre",
            "Nwangele",
            "Obowo",
            "Oguta",
            "Ohaji-Egbema",
            "Okigwe",
            "Onuimo",
            "Orlu",
            "Orsu",
            "Oru-East",
            "Oru-West",
            "Owerri-Municipal",
            "Owerri-North",
            "Owerri-West"
        ]
    },
    {
        "code": "JI",
        "name": "Jigawa",
        "lgas": [
            "Auyo",
            "Babura",
            "Biriniwa",
            "Birnin-Kudu",
            "Buji",
            "Dutse",
            "Gagarawa",
            "Garki",
            "Gumel",
            "Guri",
            "Gwaram",
            "Gwiwa",
            "Hadejia",
            "Jahun",
            "Kafin-Hausa",
            "Kaugama",
            "Kazaure",
            "Kiri kasama",
            "Maigatari",
            "Malam Madori",
            "Miga",
            "Ringim",
            "Roni",
            "Sule-Tankarkar",
            "Taura",
            "Yankwashi"
        ]
    },
    {
        "code": "KD",
        "name": "Kaduna",
        "lgas": [
            "Birnin-Gwari",
            "Chikun",
            "Giwa",
            "Igabi",
            "Ikara",
            "Jaba",
            "Jema'A",
            "Kachia",
            "Kaduna-North",
            "Kaduna-South",
            "Kagarko",
            "Kajuru",
            "Kaura",
            "Kauru",
            "Kubau",
            "Kudan",
            "Lere",
            "Makarfi",
            "Sabon-Gari",
            "Sanga",
            "Soba",
            "Zangon-Kataf",
            "Zaria"
        ]
    },
    {
        "code": "KN",
        "name": "Kano",
        "lgas": [
            "Ajingi",
            "Albasu",
            "Bagwai",
            "Bebeji",
            "Bichi",
            "Bunkure",
            "Dala",
            "Dambatta",
            "Dawakin-Kudu",
            "Dawakin-Tofa",
            "Doguwa",
            "Fagge",
            "Gabasawa",
            "Garko",
            "Garun-Mallam",
            "Gaya",
            "Gezawa",
            "Gwale",
            "Gwarzo",
            "Kabo",
            "Kano-Municipal",
            "Karaye",
            "Kibiya",
            "Kiru",
            "Kumbotso",
            "Kunchi",
            "Kura",
            "Madobi",
            "Makoda",
            "Minjibir",
            "Nasarawa",
            "Rano",
            "Rimin-Gado",
            "Rogo",
            "Shanono",
            "Sumaila",
            "Takai",
            "Tarauni",
            "Tofa",
            "Tsanyawa",
            "Tudun-Wada",
            "Ungogo",
            "Warawa",
            "Wudil"
        ]
    },
    {
        "code": "KT",
        "name": "Katsina",
        "lgas": [
            "Bakori",
            "Batagarawa",
            "Batsari",
            "Baure",
            "Bindawa",
            "Charanchi",
            "Dan-Musa",
            "Dandume",
            "Danja",
            "Daura",
            "Dutsi",
            "Dutsin-Ma",
            "Faskari",
            "Funtua",
            "Ingawa",
            "Jibia",
            "Kafur",
            "Kaita",
            "Kankara",
            "Kankia",
            "Katsina",
            "Kurfi",
            "Kusada",
            "Mai-Adua",
            "Malumfashi",
            "Mani",
            "Mashi",
            "Matazu",
            "Musawa",
            "Rimi",
            "Sabuwa",
            "Safana",
            "Sandamu",
            "Zango"
        ]
    },
    {
        "code": "KE",
        "name": "Kebbi",
        "lgas": [
            "Aleiro",
            "Arewa-Dandi",
            "Argungu",
            "Augie",
            "Bagudo",
            "Birnin-Kebbi",
            "Bunza",
            "Dandi",
            "Fakai",
            "Gwandu",
            "Jega",
            "Kalgo",
            "Koko-Besse",
            "Maiyama",
            "Ngaski",
            "Sakaba",
            "Shanga",
            "Suru",
            "Wasagu/Danko",
            "Yauri",
            "Zuru"
        ]
    },
    {
        "code": "KO",
        "name": "Kogi",
        "lgas": [
            "Adavi",
            "Ajaokuta",
            "Ankpa",
            "Dekina",
            "Ibaji",
            "Idah",
            "Igalamela-Odolu",
            "Ijumu",
            "Kabba Bunu",
            "Kogi",
            "Lokoja",
            "Mopa-Muro",
            "Ofu",
            "Ogori Magongo",
            "Okehi",
            "Okene",
            "Olamaboro",
            "Omala",
            "Oyi",
            "Yagba-East",
            "Yagba-West"
        ]
    },
    {
        "code": "KW",
        "name": "Kwara",
        "lgas": [
            "Asa",
            "Baruten",
            "Edu",
            "Ekiti (Araromi/Opin)",
            "Ilorin-East",
            "Ilorin-South",
            "Ilorin-West",
            "Isin",
            "Kaiama",
            "Moro",
            "Offa",
            "Oke-Ero",
            "Oyun",
            "Pategi"
        ]
    },
    {
        "code": "LA",
        "name": "Lagos",
        "lgas": [
            "Agege",
            "Ajeromi-Ifelodun",
            "Alimosho",
            "Amuwo-Odofin",
            "Apapa",
            "Badagry",
            "Epe",
            "Eti-Osa",
            "Ibeju-Lekki",
            "Ifako-Ijaiye",
            "Ikeja",
            "Ikorodu",
            "Kosofe",
            "Lagos-Island",
            "Lagos-Mainland",
            "Mushin",
            "Ojo",
            "Oshodi-Isolo",
            "Shomolu",
            "Surulere",
            "Yewa-South"
        ]
    },
    {
        "code": "NA",
        "name": "Nassarawa",
        "lgas": [
            "Akwanga",
            "Awe",
            "Doma",
            "Karu",
            "Keana",
            "Keffi",
            "Kokona",
            "Lafia",
            "Nasarawa",
            "Nasarawa-Eggon",
            "Obi",
            "Wamba",
            "Toto"
        ]
    },
    {
        "code": "NI",
        "name": "Niger",
        "lgas": [
            "Agaie",
            "Agwara",
            "Bida",
            "Borgu",
            "Bosso",
            "Chanchaga",
            "Edati",
            "Gbako",
            "Gurara",
            "Katcha",
            "Kontagora",
            "Lapai",
            "Lavun",
            "Magama",
            "Mariga",
            "Mashegu",
            "Mokwa",
            "Moya",
            "Paikoro",
            "Rafi",
            "Rijau",
            "Shiroro",
            "Suleja",
            "Tafa",
            "Wushishi"
        ]
    },
    {
        "code": "OG",
        "name": "Ogun",
        "lgas": [
            "Abeokuta-North",
            "Abeokuta-South",
            "Ado-Odo Ota",
            "Ewekoro",
            "Ifo",
            "Ijebu-East",
            "Ijebu-North",
            "Ijebu-North-East",
            "Ijebu-Ode",
            "Ikenne",
            "Imeko-Afon",
            "Ipokia",
            "Obafemi-Owode",
            "Odeda",
            "Odogbolu",
            "Ogun-Waterside",
            "Remo-North",
            "Shagamu",
            "Yewa North"
        ]
    },
    {
        "code": "ON",
        "name": "Ondo",
        "lgas": [
            "Akoko North-East",
            "Akoko North-West",
            "Akoko South-West",
            "Akoko South-East",
            "Akure-North",
            "Akure-South",
            "Ese-Odo",
            "Idanre",
            "Ifedore",
            "Ilaje",
            "Ile-Oluji-Okeigbo",
            "Irele",
            "Odigbo",
            "Okitipupa",
            "Ondo West",
            "Ondo-East",
            "Ose",
            "Owo"
        ]
    },
    {
        "code": "OS",
        "name": "Osun",
        "lgas": [
            "Atakumosa West",
            "Atakumosa East",
            "Ayedaade",
            "Ayedire",
            "Boluwaduro",
            "Boripe",
            "Ede South",
            "Ede North",
            "Egbedore",
            "Ejigbo",
            "Ife North",
            "Ife South",
            "Ife-Central",
            "Ife-East",
            "Ifelodun",
            "Ila",
            "Ilesa-East",
            "Ilesa-West",
            "Irepodun",
            "Irewole",
            "Isokan",
            "Iwo",
            "Obokun",
            "Odo-Otin",
            "Ola Oluwa",
            "Olorunda",
            "Oriade",
            "Orolu",
            "Osogbo"
        ]
    },
    {
        "code": "OY",
        "name": "Oyo",
        "lgas": [
            "Afijio",
            "Akinyele",
            "Atiba",
            "Atisbo",
            "Egbeda",
            "Ibadan North",
            "Ibadan North-East",
            "Ibadan North-West",
            "Ibadan South-East",
            "Ibadan South-West",
            "Ibarapa-Central",
            "Ibarapa-East",
            "Ibarapa-North",
            "Ido",
            "Ifedayo",
            "Irepo",
            "Iseyin",
            "Itesiwaju",
            "Iwajowa",
            "Kajola",
            "Lagelu",
            "Ogo-Oluwa",
            "Ogbomosho-North",
            "Ogbomosho-South",
            "Olorunsogo",
            "Oluyole",
            "Ona-Ara",
            "Orelope",
            "Ori-Ire",
            "Oyo-West",
            "Oyo-East",
            "Saki-East",
            "Saki-West",
            "Surulere"
        ]
    },
    {
        "code": "PL",
        "name": "Plateau",
        "lgas": [
            "Barkin-Ladi",
            "Bassa",
            "Bokkos",
            "Jos-East",
            "Jos-North",
            "Jos-South",
            "Kanam",
            "Kanke",
            "Langtang-North",
            "Langtang-South",
            "Mangu",
            "Mikang",
            "Pankshin",
            "Qua'an Pan",
            "Riyom",
            "Shendam",
            "Wase"
        ]
    },
    {
        "code": "RI",
        "name": "Rivers",
        "lgas": [
            "Abua Odual",
            "Ahoada-East",
            "Ahoada-West",
            "Akuku Toru",
            "Andoni",
            "Asari-Toru",
            "Bonny",
            "Degema",
            "Eleme",
            "Emuoha",
            "Etche",
            "Gokana",
            "Ikwerre",
            "Khana",
            "Obio Akpor",
            "Ogba-Egbema-Ndoni",
            "Ogba Egbema Ndoni",
            "Ogu Bolo",
            "Okrika",
            "Omuma",
            "Opobo Nkoro",
            "Oyigbo",
            "Port-Harcourt",
            "Tai"
        ]
    },
    {
        "code": "SO",
        "name": "Sokoto",
        "lgas": [
            "Binji",
            "Bodinga",
            "Dange-Shuni",
            "Gada",
            "Goronyo",
            "Gudu",
            "Gwadabawa",
            "Illela",
            "Kebbe",
            "Kware",
            "Rabah",
            "Sabon Birni",
            "Shagari",
            "Silame",
            "Sokoto-North",
            "Sokoto-South",
            "Tambuwal",
            "Tangaza",
            "Tureta",
            "Wamako",
            "Wurno",
            "Yabo"
        ]
    },
    {
        "code": "TA",
        "name": "Taraba",
        "lgas": [
            "Ardo-Kola",
            "Bali",
            "Donga",
            "Gashaka",
            "Gassol",
            "Ibi",
            "Jalingo",
            "Karim-Lamido",
            "Kurmi",
            "Lau",
            "Sardauna",
            "Takum",
            "Ussa",
            "Wukari",
            "Yorro",
            "Zing"
        ]
    },
    {
        "code": "YO",
        "name": "Yobe",
        "lgas": [
            "Bade",
            "Bursari",
            "Damaturu",
            "Fika",
            "Fune",
            "Geidam",
            "Gujba",
            "Gulani",
            "Jakusko",
            "Karasuwa",
            "Machina",
            "Nangere",
            "Nguru",
            "Potiskum",
            "Tarmuwa",
            "Yunusari",
            "Yusufari"
        ]
    },
    {
        "code": "ZA",
        "name": "Zamfara",
        "lgas": [
            "Anka",
            "Bakura",
            "Birnin Magaji/Kiyaw",
            "Bukkuyum",
            "Bungudu",
            "Gummi",
            "Gusau",
            "Isa",
            "Kaura-Namoda",
            "Kiyawa",
            "Maradun",
            "Maru",
            "Shinkafi",
            "Talata-Mafara",
            "Tsafe",
            "Zurmi"
        ]
    }
]


export const countries = [
    {"name": "Nigeria"},
    {"name": "Afghanistan"},
    {"name": "Albania"},
    {"name": "Algeria"},
    {"name": "American Samoa"},
    {"name": "Andorra"},
    {"name": "Angola"},
    {"name": "Anguilla"},
    {"name": "Antarctica"},
    {"name": "Antigua and Barbuda"},
    {"name": "Argentina"},
    {"name": "Armenia"},
    {"name": "Aruba"},
    {"name": "Australia"},
    {"name": "Austria"},
    {"name": "Azerbaijan"},
    {"name": "Bahamas (the)"},
    {"name": "Bahrain"},
    {"name": "Bangladesh"},
    {"name": "Barbados"},
    {"name": "Belarus"},
    {"name": "Belgium"},
    {"name": "Belize"},
    {"name": "Benin"},
    {"name": "Bermuda"},
    {"name": "Bhutan"},
    {"name": "Bolivia (Plurinational State of)"},
    {"name": "Bonaire, Sint Eustatius and Saba"},
    {"name": "Bosnia and Herzegovina"},
    {"name": "Botswana"},
    {"name": "Bouvet Island"},
    {"name": "Brazil"},
    {"name": "British Indian Ocean Territory (the)"},
    {"name": "Brunei Darussalam"},
    {"name": "Bulgaria"},
    {"name": "Burkina Faso"},
    {"name": "Burundi"},
    {"name": "Cabo Verde"},
    {"name": "Cambodia"},
    {"name": "Cameroon"},
    {"name": "Canada"},
    {"name": "Cayman Islands (the)"},
    {"name": "Central African Republic (the)"},
    {"name": "Chad"},
    {"name": "Chile"},
    {"name": "China"},
    {"name": "Christmas Island"},
    {"name": "Cocos (Keeling) Islands (the)"},
    {"name": "Colombia"},
    {"name": "Comoros (the)"},
    {"name": "Congo (the Democratic Republic of the)"},
    {"name": "Congo (the)"},
    {"name": "Cook Islands (the)"},
    {"name": "Costa Rica"},
    {"name": "Croatia"},
    {"name": "Cuba"},
    {"name": "Curaçao"},
    {"name": "Cyprus"},
    {"name": "Czechia"},
    {"name": "Côte d'Ivoire"},
    {"name": "Denmark"},
    {"name": "Djibouti"},
    {"name": "Dominica"},
    {"name": "Dominican Republic (the)"},
    {"name": "Ecuador"},
    {"name": "Egypt"},
    {"name": "El Salvador"},
    {"name": "Equatorial Guinea"},
    {"name": "Eritrea"},
    {"name": "Estonia"},
    {"name": "Eswatini"},
    {"name": "Ethiopia"},
    {"name": "Falkland Islands (the) [Malvinas]"},
    {"name": "Faroe Islands (the)"},
    {"name": "Fiji"},
    {"name": "Finland"},
    {"name": "France"},
    {"name": "French Guiana"},
    {"name": "French Polynesia"},
    {"name": "French Southern Territories (the)"},
    {"name": "Gabon"},
    {"name": "Gambia (the)"},
    {"name": "Georgia"},
    {"name": "Germany"},
    {"name": "Ghana"},
    {"name": "Gibraltar"},
    {"name": "Greece"},
    {"name": "Greenland"},
    {"name": "Grenada"},
    {"name": "Guadeloupe"},
    {"name": "Guam"},
    {"name": "Guatemala"},
    {"name": "Guernsey"},
    {"name": "Guinea"},
    {"name": "Guinea-Bissau"},
    {"name": "Guyana"},
    {"name": "Haiti"},
    {"name": "Heard Island and McDonald Islands"},
    {"name": "Holy See (the)"},
    {"name": "Honduras"},
    {"name": "Hong Kong"},
    {"name": "Hungary"},
    {"name": "Iceland"},
    {"name": "India"},
    {"name": "Indonesia"},
    {"name": "Iran (Islamic Republic of)"},
    {"name": "Iraq"},
    {"name": "Ireland"},
    {"name": "Isle of Man"},
    {"name": "Israel"},
    {"name": "Italy"},
    {"name": "Jamaica"},
    {"name": "Japan"},
    {"name": "Jersey"},
    {"name": "Jordan"},
    {"name": "Kazakhstan"},
    {"name": "Kenya"},
    {"name": "Kiribati"},
    {"name": "Korea (the Democratic People's Republic of)"},
    {"name": "Korea (the Republic of)"},
    {"name": "Kuwait"},
    {"name": "Kyrgyzstan"},
    {"name": "Lao People's Democratic Republic (the)"},
    {"name": "Latvia"},
    {"name": "Lebanon"},
    {"name": "Lesotho"},
    {"name": "Liberia"},
    {"name": "Libya"},
    {"name": "Liechtenstein"},
    {"name": "Lithuania"},
    {"name": "Luxembourg"},
    {"name": "Macao"},
    {"name": "Macedonia (the former Yugoslav Republic of)"},
    {"name": "Madagascar"},
    {"name": "Malawi"},
    {"name": "Malaysia"},
    {"name": "Maldives"},
    {"name": "Mali"},
    {"name": "Malta"},
    {"name": "Marshall Islands (the)"},
    {"name": "Martinique"},
    {"name": "Mauritania"},
    {"name": "Mauritius"},
    {"name": "Mayotte"},
    {"name": "Mexico"},
    {"name": "Micronesia (Federated States of)"},
    {"name": "Moldova (the Republic of)"},
    {"name": "Monaco"},
    {"name": "Mongolia"},
    {"name": "Montenegro"},
    {"name": "Montserrat"},
    {"name": "Morocco"},
    {"name": "Mozambique"},
    {"name": "Myanmar"},
    {"name": "Namibia"},
    {"name": "Nauru"},
    {"name": "Nepal"},
    {"name": "Netherlands (the)"},
    {"name": "New Caledonia"},
    {"name": "New Zealand"},
    {"name": "Nicaragua"},
    {"name": "Niger (the)"},
    {"name": "Niue"},
    {"name": "Norfolk Island"},
    {"name": "Northern Mariana Islands (the)"},
    {"name": "Norway"},
    {"name": "Oman"},
    {"name": "Pakistan"},
    {"name": "Palau"},
    {"name": "Palestine, State of"},
    {"name": "Panama"},
    {"name": "Papua New Guinea"},
    {"name": "Paraguay"},
    {"name": "Peru"},
    {"name": "Philippines (the)"},
    {"name": "Pitcairn"},
    {"name": "Poland"},
    {"name": "Portugal"},
    {"name": "Puerto Rico"},
    {"name": "Qatar"},
    {"name": "Romania"},
    {"name": "Russian Federation (the)"},
    {"name": "Rwanda"},
    {"name": "Réunion"},
    {"name": "Saint Barthélemy"},
    {"name": "Saint Helena, Ascension and Tristan da Cunha"},
    {"name": "Saint Kitts and Nevis"},
    {"name": "Saint Lucia"},
    {"name": "Saint Martin (French part)"},
    {"name": "Saint Pierre and Miquelon"},
    {"name": "Saint Vincent and the Grenadines"},
    {"name": "Samoa"},
    {"name": "San Marino"},
    {"name": "Sao Tome and Principe"},
    {"name": "Saudi Arabia"},
    {"name": "Senegal"},
    {"name": "Serbia"},
    {"name": "Seychelles"},
    {"name": "Sierra Leone"},
    {"name": "Singapore"},
    {"name": "Sint Maarten (Dutch part)"},
    {"name": "Slovakia"},
    {"name": "Slovenia"},
    {"name": "Solomon Islands"},
    {"name": "Somalia"},
    {"name": "South Africa"},
    {"name": "South Georgia and the South Sandwich Islands"},
    {"name": "South Sudan"},
    {"name": "Spain"},
    {"name": "Sri Lanka"},
    {"name": "Sudan (the)"},
    {"name": "Suriname"},
    {"name": "Svalbard and Jan Mayen"},
    {"name": "Sweden"},
    {"name": "Switzerland"},
    {"name": "Syrian Arab Republic"},
    {"name": "Taiwan (Province of China)"},
    {"name": "Tajikistan"},
    {"name": "Tanzania, United Republic of"},
    {"name": "Thailand"},
    {"name": "Timor-Leste"},
    {"name": "Togo"},
    {"name": "Tokelau"},
    {"name": "Tonga"},
    {"name": "Trinidad and Tobago"},
    {"name": "Tunisia"},
    {"name": "Turkey"},
    {"name": "Turkmenistan"},
    {"name": "Turks and Caicos Islands (the)"},
    {"name": "Tuvalu"},
    {"name": "Uganda"},
    {"name": "Ukraine"},
    {"name": "United Arab Emirates (the)"},
    {"name": "United Kingdom of Great Britain and Northern Ireland (the)"},
    {"name": "United States Minor Outlying Islands (the)"},
    {"name": "United States of America (the)"},
    {"name": "Uruguay"},
    {"name": "Uzbekistan"},
    {"name": "Vanuatu"},
    {"name": "Venezuela (Bolivarian Republic of)"},
    {"name": "Viet Nam"},
    {"name": "Virgin Islands (British)"},
    {"name": "Virgin Islands (U.S.)"},
    {"name": "Wallis and Futuna"},
    {"name": "Western Sahara"},
    {"name": "Yemen"},
    {"name": "Zambia"},
    {"name": "Zimbabwe"}
]



export const nationalities = [
    {"name": "NIGERIAN"},
    // {"name": "AFGHAN"},
    // {"name": "ALBANIAN"},
    // {"name": "ALGERIAN"},
    // {"name": "AMERICAN SAMOAN"},
    // {"name": "ANDORRAN"},
    // {"name": "ANGOLAN"},
    // {"name": "ANGUILLAN"},
    // {"name": "ANTARCTICAN"},
    // {"name": "ANTIGUAN AND BARBUDAN"},
    // {"name": "ARGENTINIAN"},
    // {"name": "ARMENIAN"},
    // {"name": "ARUBAN"},
    // {"name": "AUSTRALIAN"},
    // {"name": "AUSTRIAN"},
    // {"name": "AZERBAIJANI"},
    // {"name": "BAHAMIAN"},
    // {"name": "BAHRAINI"},
    // {"name": "BANGLADESHI"},
    // {"name": "BARBADIAN"},
    // {"name": "BELARUSIAN"},
    // {"name": "BELGIAN"},
    // {"name": "BELIZEAN"},
    // {"name": "BENINESE"},
    // {"name": "BERMUDIAN"},
    // {"name": "BHUTANESE"},
    // {"name": "BOLIVIAN"},
    // {"name": "BOSNIAN AND HERZEGOVINIAN"},
    // {"name": "MOTSWANA"},
    // {"name": "BOUVET ISLAND"},
    // {"name": "BRAZILIAN"},
    // {"name": "BRITISH INDIAN OCEAN TERRITORY (THE)"},
    // {"name": "BRUNEIAN"},
    // {"name": "BULGARIAN"},
    // {"name": "BURKINABÉ"},
    // {"name": "BURUNDIAN"},
    // {"name": "CABO VERDEAN"},
    // {"name": "CAMBODIAN"},
    // {"name": "CAMEROONIAN"},
    // {"name": "CANADIAN"},
    // {"name": "CAYMAN ISLANDER"},
    // {"name": "CENTRAL AFRICAN"},
    // {"name": "CHADIAN"},
    // {"name": "CHILEAN"},
    // {"name": "CHINESE"},
    // {"name": "CHRISTMAS ISLAND"},
    // {"name": "COCOS (KEELING) ISLANDER"},
    // {"name": "COLOMBIAN"},
    // {"name": "COMORIAN"},
    // {"name": "CONGOLESE"},
    // {"name": "CONGOLESE"},
    // {"name": "COOK ISLANDER"},
    // {"name": "COSTA RICAN"},
    // {"name": "CROATIAN"},
    // {"name": "CUBAN"},
    // {"name": "CURAÇAOAN"},
    // {"name": "CYPRIOT"},
    // {"name": "CZECH"},
    // {"name": "IVORIAN"},
    // {"name": "DANISH"},
    // {"name": "DJIBOUTIAN"},
    // {"name": "DOMINICAN"},
    // {"name": "DOMINICAN"},
    // {"name": "ECUADORIAN"},
    // {"name": "EGYPTIAN"},
    // {"name": "SALVADORAN"},
    // {"name": "EQUATORIAL GUINEAN"},
    // {"name": "ERITREAN"},
    // {"name": "ESTONIAN"},
    // {"name": "ESWATINI"},
    // {"name": "ETHIOPIAN"},
    // {"name": "FALKLAND ISLANDER"},
    // {"name": "FAROE ISLANDER"},
    // {"name": "FIJIAN"},
    // {"name": "FINNISH"},
    // {"name": "FRENCH"},
    // {"name": "FRENCH GUIANESE"},
    // {"name": "FRENCH POLYNESIAN"},
    // {"name": "FRENCH SOUTHERN TERRITORIES (THE)"},
    // {"name": "GABONESE"},
    // {"name": "GAMBIAN"},
    // {"name": "GEORGIAN"},
    // {"name": "GERMAN"},
    // {"name": "GHANAIAN"},
    // {"name": "GIBRALTAR"},
    // {"name": "GREEK"},
    // {"name": "GREENLANDIC"},
    // {"name": "GRENADIAN"},
    // {"name": "GUADELOUPE"},
    // {"name": "GUAMANIAN"},
    // {"name": "GUATEMALAN"},
    // {"name": "GUERNSEY"},
    // {"name": "GUINEAN"},
    // {"name": "GUINEA-BISSAUAN"},
    // {"name": "GUYANESE"},
    // {"name": "HAITIAN"},
    // {"name": "HEARD ISLAND AND MCDONALD ISLANDS"},
    // {"name": "VATICAN"},
    // {"name": "HONDURAN"},
    // {"name": "HONG KONG"},
    // {"name": "HUNGARIAN"},
    // {"name": "ICELANDIC"},
    // {"name": "INDIAN"},
    // {"name": "INDONESIAN"},
    // {"name": "IRANIAN"},
    // {"name": "IRAQI"},
    // {"name": "IRISH"},
    // {"name": "MANX"},
    // {"name": "ISRAELI"},
    // {"name": "ITALIAN"},
    // {"name": "JAMAICAN"},
    // {"name": "JAPANESE"},
    // {"name": "JERSEY"},
    // {"name": "JORDANIAN"},
    // {"name": "KAZAKHSTANI"},
    // {"name": "KENYAN"},
    // {"name": "I-KIRIBATI"},
    // {"name": "NORTH KOREAN"},
    // {"name": "SOUTH KOREAN"},
    // {"name": "KUWAITI"},
    // {"name": "KYRGYZSTANI"},
    // {"name": "LAOTIAN"},
    // {"name": "LATVIAN"},
    // {"name": "LEBANESE"},
    // {"name": "MOSOTHO"},
    // {"name": "LIBERIAN"},
    // {"name": "LIBYAN"},
    // {"name": "LIECHTENSTEIN"},
    // {"name": "LITHUANIAN"},
    // {"name": "LUXEMBOURGISH"},
    // {"name": "MACANESE"},
    // {"name": "MACEDONIAN"},
    // {"name": "MALAGASY"},
    // {"name": "MALAWIAN"},
    // {"name": "MALAYSIAN"},
    // {"name": "MALDIVIAN"},
    // {"name": "MALIAN"},
    // {"name": "MALTESE"},
    // {"name": "MARSHALLESE"},
    // {"name": "MARTINIQUAIS"},
    // {"name": "MAURITANIAN"},
    // {"name": "MAURITIAN"},
    // {"name": "MAHORAN"},
    // {"name": "MEXICAN"},
    // {"name": "MICRONESIAN"},
    // {"name": "MOLDOVAN"},
    // {"name": "MONÉGASQUE"},
    // {"name": "MONGOLIAN"},
    // {"name": "MONTENEGRIN"},
    // {"name": "MONTSERRATIAN"},
    // {"name": "MOROCCAN"},
    // {"name": "MOZAMBICAN"},
    // {"name": "BURMESE"},
    // {"name": "NAMIBIAN"},
    // {"name": "NAURUAN"},
    // {"name": "NEPALI"},
    // {"name": "DUTCH"},
    // {"name": "NEW CALEDONIAN"},
    // {"name": "NEW ZEALANDER"},
    // {"name": "NICARAGUAN"},
    // {"name": "NIGERIAN"},
    // {"name": "NIGERIEN"},
    // {"name": "NIUEAN"},
    // {"name": "NORFOLK ISLAND"},
    // {"name": "NORTHERN MARIANA ISLANDER"},
    // {"name": "NORWEGIAN"},
    // {"name": "OMANI"},
    // {"name": "PAKISTANI"},
    // {"name": "PALESTINIAN"},
    // {"name": "PANAMANIAN"},
    // {"name": "PAPUA NEW GUINEAN"},
    // {"name": "PARAGUAYAN"},
    // {"name": "PERUVIAN"},
    // {"name": "FILIPINO"},
    // {"name": "PITCAIRN ISLANDER"},
    // {"name": "POLISH"},
    // {"name": "PORTUGUESE"},
    // {"name": "PUERTO RICAN"},
    // {"name": "QATARI"},
    // {"name": "ROMANIAN"},
    // {"name": "RUSSIAN"},
    // {"name": "RWANDAN"},
    // {"name": "RÉUNIONESE"},
    // {"name": "SAINT BARTHÉLEMY"},
    // {"name": "SAINT HELENIAN"},
    // {"name": "SAINT KITTS AND NEVISIAN"},
    // {"name": "SAINT LUCIAN"},
    // {"name": "SAINT MARTIN (FRENCH PART)"},
    // {"name": "SAINT PIERRE AND MIQUELON"},
    // {"name": "SAINT VINCENT AND THE GRENADINES"},
    // {"name": "SAMOAN"},
    // {"name": "SAN MARINESE"},
    // {"name": "SÃO TOMÉAN"},
    // {"name": "SAUDI ARABIAN"},
    // {"name": "SENEGALESE"},
    // {"name": "SERBIAN"},
    // {"name": "SEYCHELLOIS"},
    // {"name": "SIERRA LEONEAN"},
    // {"name": "SINGAPOREAN"},
    // {"name": "SINT MAARTENER"},
    // {"name": "SLOVAK"},
    // {"name": "SLOVENE"},
    // {"name": "SOLOMON ISLANDER"},
    // {"name": "SOMALI"},
    // {"name": "SOUTH AFRICAN"},
    // {"name": "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS"},
    // {"name": "SOUTH SUDANESE"},
    // {"name": "SPANISH"},
    // {"name": "SRI LANKAN"},
    // {"name": "SUDANESE"},
    // {"name": "SURINAMESE"},
    // {"name": "SVALBARD AND JAN MAYEN ISLANDER"},
    // {"name": "SWEDISH"},
    // {"name": "SWISS"},
    // {"name": "SYRIAN"},
    // {"name": "TAIWANESE"},
    // {"name": "TAJIKISTANI"},
    // {"name": "TANZANIAN"},
    // {"name": "THAI"},
    // {"name": "TIMORESE"},
    // {"name": "TOGOLESE"},
    // {"name": "TOKELAUAN"},
    // {"name": "TONGAN"},
    // {"name": "TRINIDADIAN AND TOBAGONIAN"},
    // {"name": "TUNISIAN"},
    // {"name": "TURKISH"},
    // {"name": "TURKMEN"},
    // {"name": "TURKS AND CAICOS ISLANDER"},
    // {"name": "TUVALUAN"},
    // {"name": "UGANDAN"},
    // {"name": "UKRAINIAN"},
    // {"name": "EMIRATI"},
    // {"name": "BRITISH"},
    // {"name": "AMERICAN"},
    // {"name": "URUGUAYAN"},
    // {"name": "UZBEKISTANI"},
    // {"name": "NI-VANUATU"},
    // {"name": "VENEZUELAN"},
    // {"name": "VIETNAMESE"},
    // {"name": "BRITISH VIRGIN ISLANDER"},
    // {"name": "U.S. VIRGIN ISLANDER"},
    // {"name": "WALLIS AND FUTUNA ISLANDER"},
    // {"name": "SAHRAWI"},
    // {"name": "YEMENI"},
    // {"name": "ZAMBIAN"},
    // {"name": "ZIMBABWEAN"}
  ];
  
